services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: esbenkc/darkgpt:dev
    volumes:
      - ..:/home/darkgpt/app:cached
      - dvc-data:/home/darkgpt/app/.dvc/cache
    command: [sleep, infinity]

volumes:
  dvc-data: {}
